### ISSUE TITLE
Can't open .tar file

### ISSUE THREAD

**Issue by Dude-Bear** [gaetandi/cheXpert#1]
Hello @gaetandi!
First of all, I want to thank you for uploading this awesome repo. I just started to learn more about ML and I think I can learn a lot from your repo. 
Unfortunately, I get the error "This does not look like a tar archive" directly in my terminal when unpacking the file "model_ones_3epoch_densenet.tar".
It may well be that I make a simple beginner mistake, but unfortunately, I can not find a solution. I would be very happy about possible solutions.

OS: Ubuntu 18.04.2 LTS

![cheXpert](https://user-images.githubusercontent.com/30493095/60027517-ebb43b00-969d-11e9-826d-14475a01cf59.png)

**Comment by gaetandi** [comment]
Hello @Dude-Bear,
Thanks for your interest in our work.

Why would you like to unpack this file ?

These files are saving the densenet models and can be loaded directly in a script (as it's the case in the notebook). Trying to access this file and unpack it, if not in this situation, may not be a relevant idea.

**Comment by Dude-Bear** [comment]
Thank you for your answer @gaetandi,

okay, I will try to load them directly in a script.

Thanks again for the repository I really appreciate it.
